### ISSUE TITLE
Manual Reload of Integration required

### ISSUE THREAD

**Issue by kellerassel007** [petergridge/openweathermaphistory#42]
Last night I noticed an outage of the sensor data. It required a reload of the sensor settings and then it worked again instantly.
The days before it worked without any outage, any clues?

Debug log:  
2024-07-25 11:12:55.393 ERROR (MainThread) [custom_components.openweathermaphistory.sensor] Unexpected error fetching openweathermaphistory data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openweathermaphistory/sensor.py", line 107, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 308, in async_update
    earliestdata = min(data)
                   ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

2024-07-25 11:22:55.392 ERROR (MainThread) [custom_components.openweathermaphistory.sensor] Unexpected error fetching openweathermaphistory data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openweathermaphistory/sensor.py", line 107, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 308, in async_update
    earliestdata = min(data)
                   ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

2024-07-25 11:32:55.392 ERROR (MainThread) [custom_components.openweathermaphistory.sensor] Unexpected error fetching openweathermaphistory data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openweathermaphistory/sensor.py", line 107, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 308, in async_update
    earliestdata = min(data)
                   ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

2024-07-25 11:41:42.077 DEBUG (MainThread) [custom_components.openweathermaphistory.data] Updating from https://api.openweathermap.org/data/3.0/onecall/timemachine?
[...]

worked from here again after reload of sensor settings

**Comment by kellerassel007** [comment]
My workaround is to build an automation that monitors my sensor and trigger reload in case the sensor is unavailable for at least 1 hour:
```yaml
trigger:
  - platform: state
    entity_id:
      - sensor.<YOUR_SENSOR_ENTITY_ID>
    to: unavailable
    for:
      hours: 1
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - sensor.<YOUR_SENSOR_ENTITY_ID>
    to: unknown
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition: []
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: "{{ config_entry_id('sensor.<YOUR_SENSOR_ENTITY_ID>') }}"
```
